# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-25 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
    ]
