# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-28 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200328_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=0, upload_to='static/'),
            preserve_default=False,
        ),
    ]
